version: "3.8"

services:
  backend:
    build: .
    restart: always
    depends_on:
      - database
    ports:
      - "9000:5000"

  database:
    image: postgres:13
    restart: always
    environment:
      POSTGRES_USER: username
      POSTGRES_PASSWORD: password
      POSTGRES_DB: notesdb
    volumes: 
      - pgdata:/var/lib/postgresql/data 

volumes:
  pgdata:
    driver: local