CREATE TABLE IF NOT EXISTS "__EFMigrationsHistory" (
    "MigrationId" character varying(150) NOT NULL,
    "ProductVersion" character varying(32) NOT NULL,
    CONSTRAINT "PK___EFMigrationsHistory" PRIMARY KEY ("MigrationId")
);

START TRANSACTION;

CREATE TABLE "Notes" (
    id integer GENERATED BY DEFAULT AS IDENTITY,
    text text NOT NULL,
    done boolean NOT NULL,
    CONSTRAINT "PK_Notes" PRIMARY KEY (id)
);

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20211130132934_firstmigration', '6.0.0');

COMMIT;

